version: '2'
services:
    boot-app:
        image: boot
        external_links:
            - boot-mysql:mysql
            - boot-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/boot?useUnicode=true&characterEncoding=utf8&useSSL=false
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    boot-mysql:
        extends:
            file: mysql.yml
            service: boot-mysql
    boot-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: boot-elasticsearch
